title: Earth Data Science Portfolio
remote_theme: pages-themes/hacker@v0.2.0
plugins: 
- jekyll-remote-theme

layout:
  boomarks:
    - name: "SF Map"
    - name: "Denver Climate"
    - name: "Mountain Lions"
    - name: "Pine Ridge NDVI"
      tab: 2
  services:
    - name: "Projects"
      tab: 2
      style: row
      columns: 4
